name: Breakcraft-Survival
version: 1.1
main: de.breakcraft.survival.SurvivalPlugin
commands:
  pawnshop:
  craft:
  chunk:
  guide:
depend: [LuckPerms, Vault]
softdepend: [XConomy]
api-version: '1.21'
load: STARTUP